name: Test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: bun-${{ hashFiles('bun.lock') }}
          restore-keys: bun-
      - run: bun install
      - run: bun run test
